### ISSUE TITLE
[Feature-Request] {Build Wheels for android - depthai / depthai-sdk}

### ISSUE THREAD

**Issue by jonasMayr314** [luxonis/depthai#1049]
Hi Luxonis Team,

I am currently working with your Luxnois Cameras and I am trying to use them under android.
My goal is to run a yolov5 model on the luxonis camera and get some inference results and an image
back. During my setup, I found out that I cannot use the depthai / depthai-sdk in my python "chaquopy" 
environment in Android. 
Can you explain a good way to create the wheels for your two python packages for android_21_arm64_v8a?

Thank you in advance! 

Greetings,
Jonas Mayr

**Comment by Erol444** [comment]
Hi @jonasMayr314 ,
Android support is community-supported only, as mentioned in https://github.com/luxonis/depthai-android-jni-example

Perhaps with rvc3/rvc4 devices, it will be less of a technical effort to add proper support for other platforms (like Android and ios).
