### ISSUE TITLE
Add parameter to specify whether get_available_nnet_and_data_packets() is blocking or not

### ISSUE THREAD

**Issue by Luxonis-Brandon** [luxonis/depthai#111]
Start with the `why`:
Currently pipeline.get_available_nnet_and_data_packets() is non-blocking (returns even if no data is available), causing a high polling rate in the python script, that also increases the CPU usage. So on depthai.py, running the script with default options, I measured a 330 times/s rate.

The 'what':
So it would be great to pass a parameter to get_available_nnet_and_data_packets(), whether to block waiting for new data, or not. The non-blocking behavior may still be useful if there is additional custom processing in the python script main loop (single-threaded model).

**Comment by themarpe** [comment]
Added the capability (set by default) in develop branch (Commit: 09aa811ba0f6a239fa615e1b213d82f0428c3f1f)

Running metadata, previewout and video, It runs the loop at around 70 times/s. This number mostly reflects number of packets per second coming into host from device.

**Comment by Luxonis-Brandon** [comment]
Sweet thanks!

**Comment by Luxonis-Brandon** [comment]
This is now in the `main` (default) branch.
