### ISSUE TITLE
[Feature-Request] Log Redirect

### ISSUE THREAD

**Issue by richard-xx** [luxonis/depthai#1115]
### Start with the `why`:
Adding the feature to redirect the log output in depthai would be useful for both developers and users of the library. It would provide greater flexibility in handling and managing log information, allowing users to customize the log output based on their specific needs. By redirecting the log output, developers can choose different destinations for logs, such as storing them in a file for later analysis or sending them to a remote logging service. This feature enhances the debugging and troubleshooting capabilities of depthai and improves the overall user experience.

### Move to the `what`:
The feature that I would like to see added to depthai is the ability to redirect the log output. Currently, depthai generates log messages during its operation, which are typically printed to the console by default. However, it would be beneficial to have the option to redirect these log messages to alternative destinations, such as a file, GUI interface, or remote logging service.

**Comment by themarpe** [comment]
@richard-xx 
this is already possible by: 
 - Setting DEPTHAI_LEVEL env variable
 - Programatically using device.setLogOutputLevel & `device.setLogLevel` and `device.addLogCallback`
