### ISSUE TITLE
Higher Resolution RGB With NN Overlay

### ISSUE THREAD

**Issue by Luxonis-Brandon** [luxonis/depthai#159]
### Start with the `why`:

As requested in the [Luxonis Community](https://luxonis-community.slack.com/archives/CT79Z6GP5/p1595310543425000), it is often useful to be able to show the neural results overlaid on a higher resolution RGB preview.  Say for demos, testing at a distance, and for direct visualizations in products/etc.  As it stands now the RGB preview output is the size of the neural network itself and is not configurable (where as the left and right streams are request-able at full resolution).

And as it stands now the RGB stream is selectable at 1080p and 4K resolution, but this is without neural inference result overlay.

### Move to the `how`:

Either the H.264 stream (will need to decode and show the frames in depthai.py), or the uncompressed NV12 output of the our internal pipeline (that can be converted to BGR before displaying in python).

### Move to the `what`:

Allow higher resolution RGB with neural inference result overlay.

**Comment by pamolloy** [comment]
- [ ] Document this example on docs.luxonis.com
