### ISSUE TITLE
Save the distortion coefficients, camera intrinsic and extrinsic parameters in to EEPROM

### ISSUE THREAD

**Issue by 2emoore4** [luxonis/depthai#182]
## Start with the `Why`:
As @Luxonis-Brandon mentioned EEPROM is big enough to store it I’m sure. So, if possible we should add the following information:
- distortion coefficients of left/right/RGB
- left intrinsic
- right intrinsic
- RGB intrinsic
- Assuming right camera as the reference frame. extrinsic to left and RGB camera or from right to left and RGB.

Returning the above information using API helps the users in simulating and working with their own experiments without the necessity of calibrating again and storing this information on the host.

## The `How`:
Currently, we are writing only Homography matrix to the EEPROM. So, we just need to load this additional information and provide a function to return it.  See more information from [here](https://luxonis-community.slack.com/archives/CT79Z6GP5/p1597804778275700?thread_ts=1597775738.258200&cid=CT79Z6GP5) on saving some of these.

## The `What`:
This feature might help in converting the to point cloud externally, use different filtering, feature extraction techniques may be which are not available inside myriad X currently.

**Comment by Luxonis-Brandon** [comment]
Thanks.  @saching13 is actually looking into this.  To save these in EEPROM and make them requestable easily through the API for such purposes.

**Comment by Luxonis-Brandon** [comment]
So the EEPROM is plenty big enough to store it I’m sure.  So at least:

- left/right rectification
- left intrinsic
- right intrinsic
- RGB intrinsic
- And probably extrinsics as well if possible between the cameras.

And then we should make all of these accessible easily via the API.

**Comment by Luxonis-Brandon** [comment]
This is now implemented in https://github.com/luxonis/depthai/pull/190
