### ISSUE TITLE
tensor memory leak in openvino_tensor_representation_develop_merge

### ISSUE THREAD

**Issue by rychardeh** [luxonis/depthai#194]
To reproduce, run: `python3 depthai_demo.py -cam left_right --cnn_model openpose2`

I believe it's related to the nnet_packet.getOutputsList() and nnet_packet.getOutputsDict() calls.  A similar error was fixed in a previous version of the openvino_tensor_representation branch.

**Comment by Luxonis-Brandon** [comment]
Thanks for the report!

**Comment by szabi-luxonis** [comment]
Fixed in : 6935a56f9a65be306d1878de0c83578fe1c8649b
https://github.com/luxonis/depthai/commit/6935a56f9a65be306d1878de0c83578fe1c8649b
