### ISSUE TITLE
libf77blas.so.3: cannot open shared object file: No such file or directory.

### ISSUE THREAD

**Issue by Luxonis-Brandon** [luxonis/depthai#198]
![image](https://user-images.githubusercontent.com/32992551/93647348-7846c980-f9c5-11ea-9ab8-ba9979ecc2f1.png)

Some customer have seen the error above when using DepthAI on Raspberry Pi.

**Comment by Luxonis-Brandon** [comment]
It seems like this StackOverflow resolves the issue:
https://stackoverflow.com/questions/53784520/numpy-import-error-python3-on-raspberry-pi

sudo apt-get install python-dev libatlas-base-dev

We will make a script that checks for these dependencies and automatically installs them if they are not there.

**Comment by VanDavv** [comment]
[Script is available here](https://docs.luxonis.com/api/#supported_platforms) and one of the packages installed there is `libatlas-base-dev`
