### ISSUE TITLE
Install Scripts for Each Platform to Make Sure Dependencies are Installed

### ISSUE THREAD

**Issue by Luxonis-Brandon** [luxonis/depthai#199]
### Start with the `why`:

Most customers are running into installation issues when installing DepthAI because of missing dependencies, issues with OpenCV, numpy, etc. that are platform specific.  (See https://github.com/luxonis/depthai/issues/198 and [here](https://discuss.luxonis.com/d/51-megaai-rpi-python-build) as examples)

In these cases, engineers end up burning their time fixing the same things that other engineers are fixing in parallel.  This is  frustrating, mindless work that we should make sure only has to be done once, by us, so that other engineers don't have to keep re-solving these same problems.

In solving these problems once, for everyone, we materially add engineering efficiency to the world - which is the whole point of the platform actually: To solve problems so that other engineers don't have to - so that other engineers can focus on the higher-level problems.

So another way to say that is that the core value of DepthAI (and megaAI) is that it `just works`.  So we need to make sure we bring this value to our customers.  

### Move to the `how`:

Implement and maintain a set of installation scripts that is aware of - and automatically circumvents such install and dependency errors.  Popular platforms should then have an installation script:

 - Raspberry Pi - We should check the variants of installs below:
   - Raspberry Pi OS ([here](https://www.raspberrypi.org/downloads/raspberry-pi-os/))
     - Raspberry Pi OS (32-bit) with desktop and recommended software
     - Raspberry Pi OS (32-bit) with desktop
     - Raspberry Pi OS (32-bit) Lite
  - N00BS ([here](https://www.raspberrypi.org/downloads/noobs/))
    - NOOBS
    - NOOBS Lite
 - Jetson Series (Jetson Nano baselined)
 - Ubuntu 18.04
 - Ubuntu 20.04
 - MacOS
 - Windows 10

### Move to the `what`:

Make install scrips for DepthAI for popular platforms.

### An aside on a 'dream solution':

It will be difficult to make sure these scripts stay correct, as Raspbian, Ubuntu, etc. are constantly updating their packages/etc. and these prevent new errors/conflicts/etc. - and so there is risk that these new issues will make the existing install script obsolete relatively quickly.  

So what would be ideal would be to have a system that automatically install the latest from scratch on a variety of systems, update the OS/etc. per the OS recommendations, and then check our installation script for DepthAI.

**Comment by VanDavv** [comment]
This is implemented now [here](https://docs.luxonis.com/api/#installing-system-dependencies)
