### ISSUE TITLE
API enhancement: Feature tracking

### ISSUE THREAD

**Issue by Soar-RTD** [luxonis/depthai#201]
I could really use Feature Tracking in my cloud change project. Hope you can find time to come up with that. Thanks.

**Comment by Luxonis-Brandon** [comment]
Yes, we are planning on this for delivery with the KickStarter in December.  It will be IMU-assisted.

**Comment by Luxonis-Brandon** [comment]
Oh and I just found our other issue on this: https://github.com/luxonis/depthai/issues/146  So I'll close this one and ping you on that one @Soar-RTD so you can follow it.
