### ISSUE TITLE
Segmentation fault when requesting camera metadata for rectified_left/right

### ISSUE THREAD

**Issue by rychardeh** [luxonis/depthai#210]
On branch `openvino_tensor_representation_develop_merge`, calling `data_packet.getMetadata().getCameraName()` results in a Segmentation fault when used on streams produced by `rectified_left` or `rectified_right`.  Works fine on `left`, `right`, etc. as usual.

**Comment by Luxonis-Brandon** [comment]
Thanks for the report @rychardeh - we'll get this fixed.

**Comment by Luxonis-Brandon** [comment]
(As an update, we have been discussing internally on what is best here for handling this case and more that would come up.)

**Comment by alex-luxonis** [comment]
Should be fixed on: https://github.com/luxonis/depthai/pull/221, https://github.com/luxonis/depthai-core/pull/12
Before, the instance number (camera ID) was not populated from device side, and was random.

The same issue was also present for `disparity` / `depth` streams. Now the field is set to match with the "dominant eye" camera (the one that the disparity frame pixels are matching/aligned with). That is:
- with `-mirror_rectified true` (default), `getCameraName` returns `right`.
- with `-mirror_rectified false`, `getCameraName` returns `left`.
