### ISSUE TITLE
Add Sequence Number and Time Stamp to `jpegout` stream

### ISSUE THREAD

**Issue by Luxonis-Brandon** [luxonis/depthai#212]
### Start with the `why`:

When collecting data for later training, it may be collected on data-constrained platforms (i.e. USB2, or over a slower connection, or a connection which is pay-per-uses), so having JPEG encoding is quite useful.  But it is still necessary in many cases to associate one stream with another (and with metadata).

So it would be quite useful for the JPEG streams to have both the timestamp and also the sequence number associate 

### Move to the `how`:

We should implement this per https://github.com/luxonis/depthai/issues/211 such that the JPEG sequence number can be used to match to other data (metadata, other unencoded streams, etc.)

### Move to the `what`:

Implement the capability for the `jpegout` stream to contain both the Sequence Number and Time Stamp.

**Comment by alex-luxonis** [comment]
Also more details in the linked PR https://github.com/luxonis/depthai-core/pull/16
