### ISSUE TITLE
Question: distance measurement

### ISSUE THREAD

**Issue by abhatikar** [luxonis/depthai#218]
Hi,

I am getting 2 different distances of the same object based on what streams I enable. See the 'z' distance
When i enable on nn stream and see the previewout, i get this 
python3 depthai_demo.py  -s metaout previewout,12

![nn-only](https://user-images.githubusercontent.com/7994511/95130299-4454fd80-0754-11eb-9770-2513d110c77c.png)

But when i enable nn and disparity, i get this 
python3 depthai_demo.py  -s metaout previewout,12 disparity_color,12

![nn_and_disparity](https://user-images.githubusercontent.com/7994511/95130362-5a62be00-0754-11eb-96a4-280eca8c5b17.png)

Am i missing something ? How can we overlay the nn, depth information and disparity_color results into one ?

**Comment by alex-luxonis** [comment]
Hi @abhatikar ,
Currently the NN packet X,Y,Z calculations are not correct when `disparity` or `disparity_color` streams are enabled, but only with `depth`. We will fix this, or first prevent the usage of those streams together with X,Y,Z calc.

About the overlay, you can also try the `-bb` / `--draw-bb-depth` argument:
`./depthai_demo.py -s previewout metaout depth -bb`
The inner blue rectangle represents the area from the depth map that gets averaged for X,Y,Z calculations.

**Comment by Luxonis-Brandon** [comment]
Just as a note this is added to the roadmap to make it so XYZ calculation of the object is not wrong when `disparity` or `disparity_color` streams are requested.

**Comment by szabi-luxonis** [comment]
Check added in d1caf22 , if disparity/disparity_color stream is requested, depth calculation is disabled, and user is notified.
Will be reverted once support is added.
