### ISSUE TITLE
Error / incorrect values when calling Device methods

### ISSUE THREAD

**Issue by VanDavv** [luxonis/depthai#233]
If you experience an issue when running the following methods:

- `request_jpeg`
- `request_af_trigger`
- `get_nn_to_depth_bbox_mapping`
- `request_af_mode`
- `request_af_trigger`
- `request_jpeg`
- `send_disparity_confidence_threshold`

Please make sure you've run the [`create_pipeline`](https://docs.luxonis.com/api/#device_create_pipeline) method before any of the mentioned above.

This is a known bug, as these methods assume the pipeline is running and their purpose is to manipulate the device while it's running.
We will be implementing the fix for this in our equivalent API calls in our Gen2 Pipeline Builder #136, which will replace the current API and won't have those issues.

**Comment by Luxonis-Brandon** [comment]
This is now implemented/fixed in Gen2.  See some more information in our docs [here](https://docs.luxonis.com/projects/api/en/latest/components/nodes/video_encoder/).
