### ISSUE TITLE
Error / incorrect values returned from FrameMetadata methods

### ISSUE THREAD

**Issue by VanDavv** [luxonis/depthai#234]
FrameMetadata object is assigned to every packet that comes out of the DepthAI pipeline. 
However, not every field is being initiated, and sometimes calling them may result in strange large numbers (like `4294967295`), segfaults etc.

In most of the cases, the following methods should WORK:
- `getCameraName`
- `getInstanceNum`
- `getSequenceNum`
- `getTimestamp`

These methods will be available for frames coming from left / right / color / previewout streams. Others, like metaout or jpegout, may have these invalid.

The following methods most probably WON'T WORK:
- `getCategory`
- `getFrameBytesPP`
- `getFrameHeight`
- `getFrameWidth`
- `getFrameType`
- `getStride`

They were added a nice-to-have's, but as we migrate to #136, they won't be fixed to return correct values, and instead we'll focus on Gen2 not having these issues

**Comment by szabi-luxonis** [comment]
This is fixed in gen2 for a while.
