### ISSUE TITLE
IMX477 Driver Support

### ISSUE THREAD

**Issue by Luxonis-Brandon** [luxonis/depthai#239]
### Start with the `why`:

When working ArduCam to make M12-mount variants of the IMX378, ArduCam discovered that the IMX378 tested with M12 Mount lens cause RED tint and vignetting, likely as a result of the larger CRA of the IMX378 (which is designed for more compact lenses which have higher CRA, so there is a CRA mismatch, which results in the color and vignetting effect).

The IMX477 is largely the equivalent of the IMX477 but designed for the lower CRAs that come with surveillance (M12-mount) applications.  So it is desirable instead of the IMX378 for applications where an M12 lens is desired (as it matches the CRA of these lenses much better).

### Move to the `how`:

We have initially prototyped the IMX477 driver support.  We just need to integrated this into `main` branch of DepthAI.  It is currently in `imx477_support` branch (https://github.com/luxonis/depthai/tree/imx477_support).

### Move to the `what`:

Support the IMX477 for M12-mount 12MP color camera applications.

**Comment by alex-luxonis** [comment]
Also https://github.com/luxonis/depthai-core/pull/16
