### ISSUE TITLE
Using -brd flag with depthai_demo.py causes depth calculation error

### ISSUE THREAD

**Issue by Luxonis-Brian** [luxonis/depthai#244]
Problem:

Using the `-brd' flag with `depthai_demo.py` causes an error in the spatial coordinates of a detected object. In my limited testing (see recreation steps below), the problem results in the calculated distance being smaller than the real world distance. 

Steps to recreate:

1. Use calibrated DepthAI USB3C-OBC or OAK-D variant
2. Run `python3 depthai_demo.py` in the `develop` branch. Point device at a target a known distance away and record the distance. 
3. Run `python3 depthai_demo.py -brd bw1098obc` in the `develop` branch. Point device at a target a known distance away, and the resulting spatial coordinates will be incorrect.

**Comment by alex-luxonis** [comment]
Looks like the problem existed in both cases, at steps `2` and `3`. 
The X, Y, Z coordinates were off, caused primarily by an incorrect shift of `X` and `Y` towards the top-left corner, and this resulted in `Z` component value being reduced too, as depth is decomposed on all 3 axis.
