### ISSUE TITLE
Bugs / improvements in tests

### ISSUE THREAD

**Issue by VanDavv** [luxonis/depthai#254]
When running `integration_test.py`, I get the following warning after start

```
/home/vandavv/dev/luxonis/depthai/integration_test.py:123: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if subset.index(comb) is 0:
/home/vandavv/dev/luxonis/depthai/integration_test.py:127: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if comb is not "metaout" and limit_fps:
```
we should update the files.

Also, left, right and depth streams do not show preview when being tested (although previewout works fine). 
This is due to usage of -co flag, which does not show other streams than previewout.

`testsFunctional` fails while testing `human-pose-estimation-0001` and `object_tracker` even though these streams/models work fine when tested manually

`tests/test_cli_utils.py` does not work at all, fails with import

```
Using Custom Calibration File: depthai.calib
Traceback (most recent call last):
  File "tests/test_cli_utils.py", line 6, in <module>
    from depthai_helpers.cli_utils import parse_args, cli_print, PrintColors
ImportError: cannot import name 'parse_args' from 'depthai_helpers.cli_utils' (/home/vandavv/dev/luxonis/depthai/depthai_helpers/cli_utils.py)
```

**Comment by szabi-luxonis** [comment]
Fixed in #262
