### ISSUE TITLE
Add colorized depth map

### ISSUE THREAD

**Issue by itsderek23** [luxonis/depthai#28]
The current depth map is grayscale, but we can support a better-looking colorized depth map based on https://github.com/luxonis/depthai-python-extras/commit/0fd2cc61c6be1b75ad5eed07424a2ad509f48074#diff-b284a28710cce90d9d9be3a7f4cabc8eR165.

Add this back to the `test.py` script.

/cc @GergelySzabolcs

**Comment by itsderek23** [comment]
Ensure frame rate for doing colorization on host is acceptable as well.

**Comment by itsderek23** [comment]
Believed this was reverted in 6109ed87948bdaeefacfdf8221c7ce483304054f

**Comment by chris-piekarski** [comment]
BTW @itsderek23, I checked out the commit you reference and it changed from black & white to black & red. Regardless of the objects in the frame, I couldn't get anything but red.

**Comment by itsderek23** [comment]
Thanks @chris-piekarski - we're working on this in #37.

**Comment by szabi-luxonis** [comment]
This was added on master a while ago.
python3 test.py -s depth_sipp
or
colorized disparity
python3 test.py -s depth_color_h
