### ISSUE TITLE
Opencv import fails on Windows; ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by szabi-luxonis** [luxonis/depthai#314]
Media Feature Pack must be installed for Windows 10 N editions: 
https://support.microsoft.com/en-us/help/3145500/media-feature-pack-list-for-windows-n-editions

Source: https://github.com/skvark/opencv-python/blob/master/README.md

**Comment by Luxonis-Brandon** [comment]
Thanks.  Also added this to the Troubleshooting section here: https://github.com/luxonis/depthai-docs-website/blob/master/source/pages/troubleshooting.rst#dll-load-failed-while-importing-cv2-on-windows
