### ISSUE TITLE
Example Request of Automatically Storing JPEGs for a Detected Class

### ISSUE THREAD

**Issue by Luxonis-Brandon** [luxonis/depthai#326]
### Start with the `why`:

As more users are getting up to speed with depthai, one of the most commonly requested features is automatically saving a JPEG when a certain class is detected.  Such a thing is write-able by the end user, but we have not given advice in many locations for the same exact thing.

### Move to the `how`

We should write a canonical example of doing this, using the Gen2 pipeline builder, and add it to the code samples here: [https://docs.luxonis.com/projects/api/en/gen2_develop/](https://docs.luxonis.com/projects/api/en/gen2_develop/)

### Move to the `what`:

Make an example that automatically saves a JPEG when a certain class is detected, e.g. `person` or `tv/monitor` for the default MobileNetSSDv2 PASCAL VOC 2007-trained model.

**Comment by VanDavv** [comment]
@Luxonis-Brandon here is the initial implementation https://github.com/luxonis/depthai-experiments/pull/62

**Comment by qaqak** [comment]
> @Luxonis-Brandon here is the initial implementation [luxonis/depthai-experiments#62](https://github.com/luxonis/depthai-experiments/pull/62)

What about the other models?

**Comment by qaqak** [comment]
luxonis/depthai-experiments#62
This is not what I meant.
I meant that you can run a Python script or function whenever something is detected.

**Comment by Luxonis-Brandon** [comment]
https://github.com/luxonis/depthai-experiments/tree/master/gen2-class-saver-jpeg

**Comment by Luxonis-Brandon** [comment]
> > @Luxonis-Brandon here is the initial implementation [luxonis/depthai-experiments#62](https://github.com/luxonis/depthai-experiments/pull/62)
> 
> What about the other models?

Is there a specific model you are wanting to see?

**Comment by qaqak** [comment]
Yes
`vehicle-license-plate-detection-barrier-0106`

**Comment by Luxonis-Brandon** [comment]
So are you wanting to save when a vehicle is detected?  If so actually it's just a matter of changing the model and then the class to save.  We can write up an example if you'd like.  Thoughts?

**Comment by qaqak** [comment]
Yes, thank you.
And I am also trying run a function when a vehicle is detected.
If you want, you can see my current code

**Comment by wasauce** [comment]
@qaqak while I'm not part of the Luxonios team -- post what code you have and I'll happily take a look

**Comment by Luxonis-Brandon** [comment]
Thanks @wasauce .  And yes we'd like to see it as well.  CC: @cafemoloko .

**Comment by qaqak** [comment]
> @qaqak while I'm not part of the Luxonios team -- post what code you have and I'll happily take a look

I put it in [this repo](https://github.com/qaqak/license-plate-recognition-with-opencv) with a README.md

**Comment by Luxonis-Brandon** [comment]
Thanks.

**Comment by dhruvsheth-ai** [comment]
Hey @qaqak , I see that you are using Gen1 API to use the pre-trained OpenVINO Model. The Gen2 API is comparitively easy to customize and there are documented scripts you could follow along. Would you mind giving the Gen2 API a shot with this model. You could convert the .xml and .bin files from the OpenVINO model `vehicle-license-plate-detection-barrier-0106
` and convert to .blob file using the detailed doc page - https://docs.luxonis.com/projects/api/en/latest/tutorials/local_convert_openvino/

The OpenVINO Model is a Mobilenet V2 SSD, and fits the implementation in the gen2 class saver jpeg example - https://github.com/luxonis/depthai-experiments/tree/master/gen2-class-saver-jpeg

Also edit the labels to the one's the model would be using to ensure there are no errors
This would leave you with more room to flexibility and space for adding custom functions.
