### ISSUE TITLE
Auto-Restart doesn't work with `ctrl-c` on hanging example script

### ISSUE THREAD

**Issue by itsderek23** [luxonis/depthai#34]
#30 helped with resetting when the host app dies. 

However, I'm seeing another case where the device doesn't reset/cleanup on failure. To reproduce:

* Run `python3 example_run_landmarks_recognition.py`. It should hang (see #32).
* `ctrl-c` 2x
* Run `python3 example_run_landmarks_recognition.py` or any other script. The script will fail to start with an error like below:

```
python3 test.py
Using Custom Calibration File: depthai.calib
Using Arguments= {'config_overwrite': None}
depthai.__version__ == 0.0.9a
depthai.__dev_version__ == 35018f82c3451287cc6661c04faa764a7a58b4bc
depthai: before xlink init;
Device Found name 1.2- 
about to boot device with "cmd_file": /home/pi/Desktop/depthai-python-extras/depthai.cmd
not xlink success
depthai: Error initalizing xlink;
Error initializing device. Try to reset it.
```

**Comment by Luxonis-Brandon** [comment]
This is not fixed on Master so closing the issue.
