### ISSUE TITLE
ModuleNotFoundError: No module named 'consts'

### ISSUE THREAD

**Issue by bharath5673** [luxonis/depthai#381]
plz help .. im trying to run OAK-D with  **python run_tests.py**

and im facing thses error

```
Traceback (most recent call last):
  File "tests\tests_runner.py", line 4, in <module>
    from consts.resource_paths import nn_resource_path
ModuleNotFoundError: No module named 'consts'
```

im using conda ,, **python env ver =3.8.10**

![Screenshot (9)](https://user-images.githubusercontent.com/33729709/119217853-af442080-bafa-11eb-9db0-6ead9894fe48.png)

**Comment by alex-luxonis** [comment]
Oh, these scripts were not ported yet to Gen2, as `depthai_demo.py` is now on `main` branch.
`run_tests.py` may work on `gen1_main` branch though. As well as `calibrate.py`.

@VanDavv / @Erol444 - we should print a message and exit in these scripts, as they could confuse users.

**Comment by bharath5673** [comment]
no @alex-luxonis again im facing the same on gen1_main too :(

![Screenshot (11)](https://user-images.githubusercontent.com/33729709/119220508-7c088e00-bb08-11eb-88d6-7de736457bd7.png)

**Comment by VanDavv** [comment]
@bharath5673 could you check if the tests are now working? (PR got merged)

**Comment by bharath5673** [comment]
> @bharath5673 could you check if the tests are now working? (PR got merged)

yes its working , ty ))
