### ISSUE TITLE
XLinkOut 217 error

### ISSUE THREAD

**Issue by ltipang** [luxonis/depthai#391]
![Capture](https://user-images.githubusercontent.com/43801916/120353998-b2c67b80-c334-11eb-9130-33139b04cd0e.JPG)
Sir, I am using custom yolo blob.
When using only plate detection model, there is no error.
Btw when using 2 yolo models, I got this error.
[14442C1071022FCF00] [22.644] [system] [critical] Fatal error. Please report to developers. Log: 'XLinkOut' '217'

Help me! Thank you.

**Comment by Erol444** [comment]
Hello @ltipang ,
if the script is not proprietary, could you share the source? It would be the easiest to debug this issue. Sorry for the inconvenience and the delay!
Thanks, Erik

**Comment by szabi-luxonis** [comment]
Fixed.

**Comment by ltipang** [comment]
Thank you.
