### ISSUE TITLE
[Feature-Request] ObjectTracker node

### ISSUE THREAD

**Issue by Erol444** [luxonis/depthai#429]
### Start with the `why`:
For tracking detected objects.

### Move to the `what`:
Add support for objectTracker node inside the depthai_demo. In my opinion it should be on by default and optionally disabled.

### Move to the `how`:
Inside the create_pipeline function add objectTracker node.

**Comment by Luxonis-Brandon** [comment]
Oh good idea.  I forgot that we had this for Gen1 DepthAI Demo but not yet in Gen2.

**Comment by julled** [comment]
Using the open source Stonesoup framework sounds reasonable instead if implementing a tracker on your own:
https://stonesoup.readthedocs.io/en/latest/auto_demos/Video_Processing.html#sphx-glr-auto-demos-video-processing-py
