### ISSUE TITLE
[BUG] Previews does not have a property called host depthai_demp.py

### ISSUE THREAD

**Issue by franva** [luxonis/depthai#454]
**Describe the bug**

![image](https://user-images.githubusercontent.com/5151146/129499011-cde55f1f-9649-40a7-88e5-86e0669d5f17.png)

**To Reproduce**

1. Update the code to the latest main branch and run 
2. `python depthai_demo.py -cnn road-segmentation-adas-0001 -sync -vid /media/Workspace/Learning/Github/depthai/videos/CamVid.mp4 -sh 8`

**Expected behavior**
It will run road segmentation successfully.

**Additional context**
After I looked into the code, it seems that the latest code does not define `host` property on [Previews class](https://github.com/luxonis/depthai/blob/f8356a7ad7a09b6c51da6b3ea4d2744b4272ec44/depthai_helpers/managers.py#L166), but somehow the the [code in depthai_demo.py](https://github.com/luxonis/depthai/blob/f8356a7ad7a09b6c51da6b3ea4d2744b4272ec44/depthai_demo.py#L209) is still trying to use it.

**Comment by VanDavv** [comment]
Thanks for testing out @franva. I also noticed this issue and it's addressed in #447
