### ISSUE TITLE
[BUG] demo handler.py lack of support for video file

### ISSUE THREAD

**Issue by franva** [luxonis/depthai#456]
**Describe the bug**
In the `handler.py` for [deeplabv3p_person](https://github.com/luxonis/depthai/blob/f8356a7ad7a09b6c51da6b3ea4d2744b4272ec44/resources/nn/deeplabv3p_person/handler.py#L22), it misses the `host` value which is the video option `-vid`

**To Reproduce**
1. Run script `python depthai_demo.py -cnn road-segmentation-adas-0001 -vid /media/Workspace/Learning/Github/depthai/videos/CamVid.mp4 -sh 8`
2. Set up a break point on [line 22](https://github.com/luxonis/depthai/blob/f8356a7ad7a09b6c51da6b3ea4d2744b4272ec44/resources/nn/deeplabv3p_person/handler.py#L22), 
3. You will see that the block of code under if statement will never be executed.

**Additional context**
A quick fix is to add `host` inside the bracket.
e.g. `if name in (Previews.color.name, Previews.nn_input.name, 'host'):`

But a proper fix should be applied here.

**Comment by Luxonis-Brandon** [comment]
Thanks for the report @franva and thanks for the quick fix here @VanDavv !
