### ISSUE TITLE
[Feature-Request] Provide the exterior 3D models for OAK-1 and OAK-D cameras

### ISSUE THREAD

**Issue by franva** [luxonis/depthai#467]
### Start with the `why`:
I'm designing my system in 3D and would like to integrate the camera into my hardware.

### Move to the `what`:
I'd like to see the 3D models are provided, just for exterior is enough.

### Move to the `how`:
A `.stl` or `.obj` file will be enough

**Comment by Erol444** [comment]
Hello @franva ,
enclosure step files should be available at https://github.com/luxonis/depthai-hardware/tree/master/Mechanical%20designs
There are also 3D pcb files for all devices on that Github repo. 
Thanks, Erik

**Comment by franva** [comment]
lovely~! thanks ~!
