### ISSUE TITLE
[BUG] RuntimeError: Failed to find device (ma2480), error message: X_LINK_DEVICE_NOT_FOUND

### ISSUE THREAD

**Issue by Erol444** [luxonis/depthai#514]
When running a DepthAI example on your OAK device, you might come across:
```
RuntimeError: Failed to find device (ma2480), error message: X_LINK_DEVICE_NOT_FOUND.
```

**To fix this**, set the udev rules using the commands below, unplugging DepthAI and then plugging it back into USB afterwards.
```
echo 'SUBSYSTEM=="usb", ATTRS{idVendor}=="03e7", MODE="0666"' | sudo tee /etc/udev/rules.d/80-movidius.rules
sudo udevadm control --reload-rules && sudo udevadm trigger
```

**Comment by BhooshanDeshpande** [comment]
How to resolve this for OAKD - POE version?

**Comment by brmarkus** [comment]
Have you set-up the udev-rules?
Are you using a Linux-OS, which OS?
Can you describe your environment (SW and HW), please?
Do you use an USB-hub, connected via USB2 or USB3, is the hub powered?
Can you share the output of "lsusb" right after connecting your device - as well as after starting your application, please?
Can you share the output of "dmesg" from the moment before connecting the device, please?
(the MyriadX device first appears as a HighSpeed-device; after starting the application and initializing it disappears from USB-bus and appears as SuperSpeed-device again)

**Comment by TheBricktop** [comment]
Im suddenly having the same problem, win10 fresh new venv of python 3.8.5 and newest depthai and opencv contrib, lens is clicking but XLINK error breaks the program.

**Comment by brmarkus** [comment]
Do you use the "original USB3 cables", are you sure they are USB3-capable? Do you have an actively powered USB-hub inbetween? Are you sure you connected the USB3-cable into a USB3-capable port on your machine?
