### ISSUE TITLE
[BUG] Trouble installing in Windows 10

### ISSUE THREAD

**Issue by boardgameplayer74** [luxonis/depthai#599]
Hi guys,

I received my OAK D Lite package last week and am trying to install it on a Windows machine using the provided installer.
When I run the installer (3.0.5 version) it seems to function normally without any errors, but when I run the program I get the following error:

![image](https://user-images.githubusercontent.com/38844357/148101766-0f2c39f3-bc7b-41d8-b774-79ea51dfb29f.png)

I have python 3.9 installed on my computer (from the windows store).
Here is my system information:
![image](https://user-images.githubusercontent.com/38844357/148102142-10e53b26-7513-41e4-8977-ff025e4cedba.png)

When this didn't work I also uninstalled the depthai software and tried the manual method using chocolatey to install components and use venv.  This ultimately led me to the same error, although sometimes I got an addition, different error:

![DepthAI 2022-01-03 171336](https://user-images.githubusercontent.com/38844357/148102352-d617e08b-f56e-435d-910b-4053c4e38bf5.png)

**Comment by boardgameplayer74** [comment]
I noticed a couple of warning during the manual install and I'm not sure if these are relevant:
![image](https://user-images.githubusercontent.com/38844357/148104591-40793270-55b7-4aca-8312-030a2dbce486.png)
![image](https://user-images.githubusercontent.com/38844357/148104644-43684b6c-9bf6-40b3-8700-080e6518ecbb.png)

**Comment by boardgameplayer74** [comment]
This is the error I get when I tried after manually installing:
![image](https://user-images.githubusercontent.com/38844357/148104941-9eae4adc-a729-4464-969b-df4b900935e3.png)

**Comment by Luxonis-Brandon** [comment]
Sorry about the trouble here.  We have fixed this in 3.0.6 and then with additional corner-case improvements in 3.0.7:
[https://github.com/luxonis/depthai/releases](https://github.com/luxonis/depthai/releases)

Would you mind giving those a shot?

Thanks again,
Brandon

**Comment by boardgameplayer74** [comment]
It looks like it was a cable issue.  I noticed the error codes said something about low speed usb, so I switched to a different cable and it worked!
