### ISSUE TITLE
Doubt about epipolar error

### ISSUE THREAD

**Issue by vipulkumar-developer** [luxonis/depthai#646]
Hi, I'm trying to calibrate the OAK-D Lite camera with the file calibrate.py using the specified branch.
My question is not a problem but a doubt: once I've finished the calibration, a window appears where is written the value for epipolar error. What interval of epipolar error values is acceptable?

**Comment by themarpe** [comment]
CC: @saching13

**Comment by saching13** [comment]
In factory we do below 0.5. 
For user I have set it to 1.0 to allow for extreme conditions. 

For better accuracy it would be preferable to be below 0.7.

**Comment by vipulkumar-developer** [comment]
Ok, thank you very much.
