### ISSUE TITLE
[Feature-Request] Add capture timer/countdown to calibration

### ISSUE THREAD

**Issue by diablodale** [luxonis/depthai#668]
### Start with the `why`:

I need the capture of images during calibration to be "hands-off". I am working alone and 2 meters away from the keyboard holding a 80x60cm aluminum calibration target that requires two hands.

### Move to the `what`:

Request an automated timer or countdown for all image captures that is enabled with a parameter. For example `[-t timerseconds]`
When this param is given, a timer is started and the image capture is triggered after the given number of seconds. Errors/retries continue to require keyboard input.

### Move to the `how`:

I hacked a fixed 10 seconds with 8 lines https://github.com/diablodale/depthai/commit/445479f9d9b3b2b7f2316913f8bed534e5619876
Should be easy to add param support. And if you want to be fancy...even overlay countdown text on top of the images.

**Comment by Luxonis-Brandon** [comment]
Good idea.  Actually it makes me think of using @geaxgx body-prefocusing or similar to just allow some sort of gesture as a trigger to capture.  Hands are taken, so it makes me think of those smile-cameras.  "Smile to capture".

Doing a timer as you propose is best though at least to start as it's so simple.  CC: @saching13 .

**Comment by diablodale** [comment]
IMHO: for accessibility and for those that are other-abled, tracking a body part or facial expressions could introduce barriers. Yes... I get the demo-tie-in of tech... though I would prefer a trigger that everyone can universally use on a utility like this (versus a demo/example).

**Comment by saching13** [comment]
Sounds good. 
@daxoft When you get back on this task let's add this feature too on the new window. Lets add the `capture` button along with a `timer slider` next to it. Which can be modified from 1-30 seconds.

**Comment by Erol444** [comment]
Added here: https://github.com/luxonis/depthai/commit/3463d38d557921b6f6f05f4cd8f559d5ec1598ea
