### ISSUE TITLE
[BUG] {Incorrect spatial location for Yolo detections}

### ISSUE THREAD

**Issue by ZeicBeniamin** [luxonis/depthai#693]
**Describe the bug**
Bounding box of the YoloSpatialDetectionNetwork doesn't overlap the location of the detected object, thus resulting in incorrect distance estimates, especially on the z (depth) axis.

**To Reproduce**
1. Just run the 'RGB&TinyYolo with Spatial Data' example from your website [here:](https://docs.luxonis.com/projects/api/en/latest/samples/SpatialDetection/spatial_tiny_yolo/#rgb-tinyyolo-with-spatial-data)
2. Set the bounding box factor to one, i.e. `setBoundingBoxScaleFactor(1)`. (You can leave it as it is, but the problem will be better observed with a larger bounding box.)
3. Place an object (a bottle, for example) that is identified by the neural network in front of the camera and observe how the bounding box in the depth image DOES NOT align with the actual object detected by the neural network.

**Expected behavior**
The bounding box surrounding the object from the NN image should surrond the same object in the depth image.

**Screenshots**
In the GIF attached below, you can see that the roundabout sign is correctly detected by the NN and subsequently framed in a bounding box, but in the depth image, the bounding box is to the right of the object, barely capturing some of the left margin of the object under it. This leads to incorrect depth estimation, that is dependent on the background of the object.

![try3](https://user-images.githubusercontent.com/28898262/165835225-4a9aa1c1-2962-4466-87f3-3c423a7abb19.gif)

**Comment by ZeicBeniamin** [comment]
If the issue has already been solved in another branch/commit (though I doubt it), please paste a link here. 
Or if you have any suggestions as to where modifications should be made, I would greatly appreciate it, since I need to get this feature working as fast as possible.
Thank you!

**Comment by Luxonis-Brandon** [comment]
Sorry about the trouble.  I think what we need to do is enable RGB-Depth alignment by default on this example.  I could be wrong though so I'm tagging @szabi-luxonis on this.

**Comment by szabi-luxonis** [comment]
@ZeicBeniamin 
We recently enabled in `develop` branch.
See here:
https://github.com/luxonis/depthai-python/blob/develop/examples/SpatialDetection/spatial_tiny_yolo.py#L85

**Comment by ZeicBeniamin** [comment]
Thank you very much, that worked for me.

Just a suggestion for the example linked in @szabi-luxonis' comment:
Maybe you would like to add `stereo_depth.setOutputSize(width=416, height=416)
` to the depth map otherwise, the depth preview fills the entire screen. I don't know if there are any performance drawbacks if you set the depth output to a smaller dimension, but a window that doesn't fill the entire screen when you first run the example certainly looks nicer. :)

**Comment by ZeicBeniamin** [comment]
Thank you again for the modification. :)

**Comment by szabi-luxonis** [comment]
> Thank you again for the modification. :)

@ZeicBeniamin  https://github.com/luxonis/depthai-python/commit/8bfded16a5736aebdf5fe4c69ba6ec6aff2c0064

**Comment by Cupcee** [comment]
Hi, I still experience this issue and I use the code in this example https://docs.luxonis.com/projects/api/en/latest/samples/SpatialDetection/spatial_mobilenet/ which has the modification done by @szabi-luxonis 

The bounding box of the depth image is not on top the person in front of the camera unless he/she goes very close to the camera. This leads to wrong results from the spatial location calculator

**Comment by ZeicBeniamin** [comment]
The fix is to align the stereo depth image with the RGB.
Code for doing that: `stereo.setDepthAlign(dai.CameraBoardSocket.RGB)`

**Comment by Cupcee** [comment]
The develop branch modifications are in the script I linked. Despite this the issue persists

**Comment by szabi-luxonis** [comment]
@Cupcee are you using the latest release?

**Comment by Cupcee** [comment]
> @Cupcee are you using the latest release?

I added a new issue on this https://github.com/luxonis/depthai/issues/700 see that for more details
