### ISSUE TITLE
RuntimeError: No available devices on NVIDIA Jetson Xavier (Oak-D)

### ISSUE THREAD

**Issue by jackfaubshner** [luxonis/depthai#699]
Hello,

I am trying to interface the Oak-D camera with the NVIDIA Jetson Xavier.

I follow this guide word by word:
https://docs.luxonis.com/projects/api/en/latest/install/#jetson

But in the end I am running into the following error when I run rbg_preview.py:
![Error 1](https://user-images.githubusercontent.com/105614709/168503192-e5c3f7fb-b8cd-47b1-b239-d95e790528df.jpg)

I cannot even see the name of the device in lsusb (although its ID is there).

However, when I do a dmsg -w, I can see the device.
![Error 2](https://user-images.githubusercontent.com/105614709/168503242-a61ebc02-67b4-4903-ac9f-b2fef3565e3c.jpg)

Can someone help me out?

Sorry about the crappy quality photos, it was easier to take pictures than to transfer screenshots on that computer.

**Comment by brmarkus** [comment]
Do you use a USB3 capable cable to connect the OAK-D?
Do you think your Jetson device is providing enough power to the OAK-D?
Can you test and connect the OAK-D to an actively powered USB3-capable USB-Hub?

The device "idVendor=03e7, idProduct=2485" is the MyriadX device.

Are you sure you installed the UDEV-rule?

**Comment by sanatmharolkar** [comment]
Hi, I am having the same issue. I have installed the udev rule and I even checked with a powered USB hub. However the device is still not recognised when I check with lsusb.
![lsusb](https://github.com/luxonis/depthai/assets/7371825/cde2b3ff-8616-40a1-82a2-01911b7dd9a6)
