### ISSUE TITLE
[Question] Use 90 degree rotation of the camera

### ISSUE THREAD

**Issue by akaneko1019** [luxonis/depthai#710]
I was able to find an option to rotate the camera 180 degrees. 
However, I couldn't find an API to rotate it by 90 degrees.
Is it possible to rotate it 90 degrees and use it?

**Comment by Luxonis-Brandon** [comment]
Yes.  The ImageManip node is used for this.  CC: @Erol444 on how to use it.

**Comment by Erol444** [comment]
Hello @akaneko1019 , you can use ImageManip for that, see [example code here](https://docs.luxonis.com/projects/api/en/latest/samples/ImageManip/image_manip_rotate/#imagemanip-rotate).
Thanks, Erik

**Comment by akaneko1019** [comment]
Thank you very much for your response.
