### ISSUE TITLE
[BUG] Can't run default demo

### ISSUE THREAD

**Issue by kannwism** [luxonis/depthai#712]
When following the [First Steps with DepthAI](https://docs.luxonis.com/en/latest/pages/tutorials/first_steps/) tutorial, I get stuck when running:

`python3 depthai_demo.py`

I get the following errror:
![image](https://user-images.githubusercontent.com/18029781/173096635-7c5f6db8-3998-45a9-8811-dee3de33aff8.png)

Basically saying that it can't download .blob model at http://artifacts.luxonis.com/artifactory/blobconverter-backup/blobs/mobilenet-ssd_openvino_2022.1_6shave.blob

Why can I not download this model?

**To Reproduce**
Run `python3 depthai_demo.py`

**Expected behavior**
A shiny smooth demo.

**Additional context**
Python 3.8.13; depthai 2.16.0.0; depthai-sdk 1.20; OAK-D Lite Camera; Ubuntu 20.04

**Comment by szabi-luxonis** [comment]
Thanks for the report, we will fix it.
https://github.com/luxonis/depthai/pull/707/commits/e43de535829309afabdbdea746c054e4403e6baf

Cc: @saching13 on testing the code after modifying, next time

**Comment by saching13** [comment]
> Thanks for the report, we will fix it.
> 
> https://github.com/luxonis/depthai/pull/707/commits/e43de535829309afabdbdea746c054e4403e6baf
> 
> 
> 
> Cc: @saching13 on testing the code after modifying, next time

Sorry. My bad. Just tested calibration scripts. Didn't realize it would affect blob somehow. Changing back to 2.15.5

**Comment by szabi-luxonis** [comment]
Fixed it in https://github.com/luxonis/depthai/commit/cbbbbdb603c8392945a6e2b542b6d62b2a6571c1
CC was just informational, no worries.

**Comment by saching13** [comment]
Aah ok.

**Comment by szabi-luxonis** [comment]
@kannwism can you confirm that latest demo is working?

**Comment by kannwism** [comment]
Demo works for me :+1: Thank you for reacting so quickly! 

Can be closed now from my side.
