### ISSUE TITLE
[Feature-Request] {Title of feature request}

### ISSUE THREAD

**Issue by SharathRC** [luxonis/depthai#717]
Hi, I have a couple of OAK POE luxonis cameras on another network.
How can I connect to them via their IP?
I can ping them already. But so far the code returns as no devices found.
I already used the documentation to manually set the IP. [link to doc](https://docs.luxonis.com/projects/hardware/en/latest/pages/guides/getting-started-with-poe.html#manually-specify-device-ip)
But this code connects to random cameras each time. I set the device_info.desc.name and it gives me a deprecation warning.

**Comment by Erol444** [comment]
@SharathRC I believe that on `develop` branch of depthai we already support this when specifying the IP of the camera (as you linked to docs). Could you try that out?
Thanks, Erik
