### ISSUE TITLE
[critical] Fatal error. Please report to developers. Log: 'ImageManipHelper' '61'

### ISSUE THREAD

**Issue by rsing92** [luxonis/depthai#730]
Hello.
I got the following error when trying to do image operations on the video output of ColorCamera.
I have seen similar issues, but they have different error number:
261: https://github.com/luxonis/depthai-core/issues/372
59: https://discuss.luxonis.com/d/258-error-with-imagemanip

I'm using depthai 2.16.0.0

**Comment by rsing92** [comment]
I figured it out from the other issues, need to use `image_manip_refactor` branch.
But how do I combine with UVC?

**Comment by Luxonis-Brandon** [comment]
I think @Erol444 mentioned that we'll be merging these next week.  Sorry about the trouble here.

**Comment by rsing92** [comment]
Thanks @Luxonis-Brandon 
Unfortunately I spent quite a few days trying to figure out how to merge functionalities from different branches with no success.
For what it's worth I have time to work on my project only after work, and in weekends. For me UVC works just fine, but I would like to combine with different functionalities. It would be great having all in one library, so the user doesn't have to worry about low-level details. I don't personally know how to combine different github branches. 

Happy sunday!

**Comment by Erol444** [comment]
Hi @rsing92,
Similar to [discussion here](https://discuss.luxonis.com/d/642-using-imagemanip-with-uvc), these are firmware features on different branches so you can't solve this with mixing depthai-python branches (`image_manip_config` and `gen2_uvc`). I believe we will be merging image_manip_refactor next week, and after that we might update the `gen2_uvc` branch to contain the latest features of imageManip. Thoughts?
Thanks, Erik

**Comment by rsing92** [comment]
This issue is fixed in latest release, however UVC is still not available.
