### ISSUE TITLE
How to use OAK-D on Raspberry Pi

### ISSUE THREAD

**Issue by 2640546445** [luxonis/depthai#743]
You guys have prepared a system image, but I want to use my own system image, how can I install depthai

**Comment by Erol444** [comment]
Hello @2640546445 ,
You can see all the steps and changelogs in [this document](https://docs.google.com/document/d/1c4JhIY2ulcgaaycUBOsAbUI1EJ_7Zx4ux4alaxFc_ts/edit) (doc linked from [here](https://docs.luxonis.com/projects/hardware/en/latest/pages/guides/raspberrypi.html#using-pre-configured-rpi-os-image)). I hope this helps!
Thanks, Erik
