### ISSUE TITLE
[BUG] NameError: name ''App is not defined

### ISSUE THREAD

**Issue by spider-x** [luxonis/depthai#750]
When i press in the depthai gui button for running oak-d lite as webcam it shows me error and camera is showing as webcam.
When i run command python depthai_demo.py --app uvc it is working properly.
![image](https://user-images.githubusercontent.com/413210/180140099-d5926fdf-1123-4ed3-8f30-e236ca505dd5.png)

**Comment by Erol444** [comment]
Hi @spider-x ,
Have you installed requirements `python install_requirements.py` before starting the depthai demo app?
Thanks, Erik

**Comment by spider-x** [comment]
> Hi @spider-x , Have you installed requirements `python install_requirements.py` before starting the depthai demo app? Thanks, Erik

No, i have used windows installer to install the depthai. I would like to ask also if is there another command than python depthai_demo.py --app uvc to run the camera as webcam. I'm asking because, everytime i run this command, it downloads and install some things and it is time-consuming.  Tahnk you for you help.

**Comment by moratom** [comment]
Hi @spider-x @Erol444. I am able to reproduce the bug - it exists both on Windows and Linux. 
Looking into it now.

**Comment by moratom** [comment]
The issue should be fixed in the #752 PR @spider-x @Erol444.
