### ISSUE TITLE
Unable to locate package libdc1394-dev

### ISSUE THREAD

**Issue by RAO-3D** [luxonis/depthai#833]
Similar to earlier issue ( https://github.com/luxonis/depthai/issues/807#issue-1396735834) 

I am using earlier version of Ubuntu (18.04 Bionic) and get:

_Reading package lists... Done
Building dependency tree      
Reading state information... Done
E: Unable to locate package libdc1394-dev_

_Failed installing dependencies. Could be a bug in the installer or unsupported platform. Open a bug report over at https://github.com/luxonis/depthai - exited with status 100 at line 132_

Must I update to Ubuntu 21.10 ?

**Comment by themarpe** [comment]
@RAO-3D we support Ubuntu 20.04 and Ubuntu 22.04

That'd be the simplest to get up and running.

Otherwise you can install the udev rules manually and use the examples and library over at `depthai-python` as is.

**Comment by RAO-3D** [comment]
Thanks - Updated and got things working.
