### ISSUE TITLE
[BUG] {Running install_requirements.py fails on jetson xavier nx (ubuntu 20.04)}

### ISSUE THREAD

**Issue by s183898** [luxonis/depthai#836]
I am trying to run "install_requirements.py"

**I get the following errors:**

ERROR: Could not find a version that satisfies the requirement for PySide2 (from depthai-sdk) (from versions: none)
ERROR: No matching distribution found for PySide2
Traceback (most recent call last):
  File "install_requirements.py", line 43, in <module>
    subprocess.check_call(pip_package_install + ["-r", "requirements.txt"], cwd=scriptDirectory)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/dmri/.virtualenvs/depthAI/bin/python3', '-m', 'pip', 'install', '-U', '--prefer-binary', '-r', 'requirements.txt']' returned non-zero exit status 1.

**Expected behavior**
Installation of requirements

**Additional context**
I have followed the guide on the website: https://docs.luxonis.com/projects/api/en/latest/install/#installation
and have created and activated the virtual environment.

pip 22.3.1
Python version: 3.8.10
Nvidia jetson xavier NX - Ubuntu 20.04

I hope you can help

**Comment by themarpe** [comment]
@s183898 
Is this the full log? Not sure why the warning would fail that command. CC: @daxoft to cross check

**Comment by s183898** [comment]
No, this is not the full log, sry, I just added the parts with either warning or error, and somehow missed the actual errors. I have edited the post. After doing some browsing I think the problem is that PySide2 does not exist for arm-processors which the Jetsons uses. If this is the case, however, I dont understand why luxonis insists that depthai is easy to set up with Jetson products.

**Comment by Erol444** [comment]
cc @daniilpastukhov ^

**Comment by s183898** [comment]
Okay sorry about that, I will remember that for the future. Thanks, I will try it out.

**Comment by s183898** [comment]
Git checkout v3.2.0 worked! thanks a lot

**Comment by s183898** [comment]
Are you going to fix this in the near future, or will I have to stay on the old git branch?

**Comment by daniilpastukhov** [comment]
The error should be fixed now, can you please try pulling and trying to install requirements again?

**Comment by s183898** [comment]
Both the install_requirements.py and depthai_demo.py works on main now. Great job and thanks for the help. I am closing the issue.
