### ISSUE TITLE
depth_color_h visualization Improvement

### ISSUE THREAD

**Issue by Luxonis-Brandon** [luxonis/depthai#90]
Following notes from Alex on Slack:
The `depth_color_h` could be enhanced actually, it only uses 64 disparity levels, lines 7 to 70 here: https://github.com/luxonis/depthai-api/blob/master/shared/disparity_luts.hpp

The rest are zero, so mapped to black color for objects in close proximity. Gives a false impression of reaching the disparity limit.

We should just construct a better LUT there.

**Comment by Luxonis-Steven** [comment]
added colormap on disparity, on python frontend. Now disparity output shows in more blue range instead of mapped to black color. Thoughts @Luxonis-Brandon ?
![image](https://user-images.githubusercontent.com/65001216/86031631-16994380-ba04-11ea-865d-0aae32cf9840.png)

**Comment by Luxonis-Brandon** [comment]
This is implemented in https://github.com/luxonis/depthai/pull/148

**Comment by Luxonis-Brandon** [comment]
Was merged this weekend.  :-)
