### ISSUE TITLE
[BUG] bash: line 231: cho: command not found

### ISSUE THREAD

**Issue by Bengt** [luxonis/depthai#918]

**Comment by Erol444** [comment]
Hi @Bengt  Could you perhaps provide some additional description that would help us debug this issue?
Thanks, Erik

**Comment by Bengt** [comment]
Hi, yes, sorry. I was still debugging this. The error occurred when running the installer script:

    sudo wget -qO- https://docs.luxonis.com/install_depthai.sh | bash

It worked anyway and I could manually run the application under `~/Luxonis`

**Comment by Bengt** [comment]
Some googling points to possibly this meaning `echo`, but the `e` was somehow lost in translation somewhere. - Just an idea.

**Comment by Erol444** [comment]
Hi @Bengt ,
Could you provide the full log you get when executing that command? What OS are you using?

![image](https://user-images.githubusercontent.com/18037362/214712693-f3cc150c-d7a1-4f17-9507-920c2dacc097.png)

Looking at https://docs.luxonis.com/install_depthai.sh it looks correct to me, not sure how it could come to parsing issues..
Thanks, Erik

**Comment by Bengt** [comment]
This was under Ubuntu 22.04.

**Comment by themarpe** [comment]
Thanks for the report @Bengt  its acutally inline with one other issue we had.

@PetrNovota do you mind searching through all use cases of the `$'` and replace with more appropriate equivalents?

**Comment by PetrNovota** [comment]
@Bengt thank you for reporting this error. 
@themarpe I have created a PR.
 I have noticed another unwanted behavior. The script does not wait for user input. Lets see if that is also solved by this. 
Strange to me is that if I run the script locally it works as expected, but running it via `sudo wget -qO- https://docs.luxonis.com/install_depthai.sh | bash` produces different and unwanted behavior

**Comment by PetrNovota** [comment]
@themarpe the PR is done. read command did not work properly. Had to specify ` < /dev/tty`
