### ISSUE TITLE
ImportError: cannot import name 'Previews' from 'depthai_sdk' 

### ISSUE THREAD

**Issue by nonathecoda** [luxonis/depthai#934]
On Ubuntu 22.04, using WSL 2

Error launching demo:
Traceback (most recent call last):
  File "/home/nona/depthai/depthai_demo.py", line 1051, in <module>
    runQt()
  File "/home/nona/depthai/depthai_demo.py", line 584, in runQt
    from gui.main import DemoQtGui
  File "/home/nona/depthai/gui/main.py", line 16, in <module>
    from depthai_sdk import Previews, resizeLetterbox, createBlankFrame
ImportError: cannot import name 'Previews' from 'depthai_sdk' (/home/nona/.local/lib/python3.10/site-packages/depthai_sdk/__init__.py)

reinstalled everything, but still won't work

**Comment by ChemiKyle** [comment]
Bit of a hack, but I got around this by just adding the following line to `~/.local/lib/python3.9/site-packages/depthai_sdk/__init__.py`

```python
from depthai_sdk.previews import *
```

**Comment by themarpe** [comment]
Addressed in latest main. Let me know if that works for you
