### ISSUE TITLE
[ibm_db installation Issue : Mac OS Ventura] {Getting requirements to build wheel}

### ISSUE THREAD

**Issue by onurbryant** [luxonis/depthai#940]
I'm trying to install ibm_db in python3 version 3.11 with the line "pip3 install ibm_db" on the terminal

I'm using Mac OS Ventura on an M1 Pro:

The error code that I get is below : 

Collecting ibm_db
  Using cached ibm_db-3.1.4.tar.gz (1.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      Detected 64-bit Python
      Arm64 architecture is not supported. Please install intel-only (x64) version of python and then install ibm_db.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by themarpe** [comment]
@onurbryant this doesn't seems related to DepthAI installation. Please provide more information, otherwise closing for now
