### ISSUE TITLE
[SDK Feature-Request] SDK example docs pages

### ISSUE THREAD

**Issue by Erol444** [luxonis/depthai#988]
### Start with the `why`:
A good documentation page is always critical for any API/library, this addition would nicely supplement the https://github.com/luxonis/depthai/pull/956 PR. Another benefit would be that we can link some examples from docs (eg. for support), instead of linking source code.

### Move to the `what`:
For each `depthai_sdk/example` add a documentation page. Add some information about the example, a demo video/image, some things to note, demos pipeline graph, its code, and link to github. So very similar to how we have [Code samples docs for depthai API](https://docs.luxonis.com/projects/api/en/latest/tutorials/code_samples/).

### Move to the `how`:
Some manual work:)

**Comment by jakaskerl** [comment]
#1070
